name: Full Build

on:
  push:
    branches:
      - master
      - 'packaging/**'
  release:
    types: [published, prereleased]
env:
  python_version: '3.10.0'

jobs:

  linux:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install Linux Dependencies
        uses: ./.github/actions/linux_dependencies
      - name: Set up Python with Debug
        uses: ./.github/actions/debug_python
        with:
          python-version: ${{ env.python_version }}
          xvfb_command: 'xvfb-run'
