name: Full Build

on:
  push:
    branches:
      - master
      - 'packaging/**'
  release:
    types: [published, prereleased]
env:
  python_version: '3.10.0'

jobs:

  linux:
    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install Linux Dependencies
        uses: ./.github/actions/linux_dependencies
      - name: Set up Python with Debug
        uses: danyeaw/setup-python-debug/.github/actions/debug_python
        with:
          python-version: ${{ env.python_version }}
          xvfb_command: 'xvfb-run'
      - name: Install Poetry
        run: $RUNNER_TOOL_CACHE/Python/${{ inputs.python-version }}/x64/bin/python -m pip install poetry==1.1.11
        shell: bash
      - name: Configure Poetry
        run: poetry config virtualenvs.in-project true
        shell: bash
      - name: Install Python Dependencies
        run: poetry install
        shell: bash
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - name: Test with Pytest
        run: xvfb-run poetry run poe test-all
        shell: bash
